In [2]:
#จัดการ/ปรับแต่งข้อมูล

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')
df.head(5)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered
1,T002,2026-01-01,C1002,USB-C Cable,NaN,2.0,12.50,25.00,PayPal,Shipped
2,T003,2026-01-02,C1003,Phone Case,Accessories,NaN,15.99,15.99,Debit Card,Processing
3,T004,2026-01-02,NaN,Laptop Stand,Office,3.0,34.99,104.97,Credit Card,Delivered
4,T005,2026-01-03,C1005,Keyboard Mechanical,Electronics,1.0,NaN,89.99,Apple Pay,Shipped

In [5]:
df.tail(5)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status
15,T016,NaN,C1014,Desk Organizer,Office,1.0,24.99,24.99,Debit Card,Processing
16,T017,2026-01-09,C1015,USB Hub 7 Port,Electronics,NaN,34.99,34.99,Credit Card,Shipped
17,T018,2026-01-09,NaN,Pen Set Premium,Office,3.0,16.99,50.97,PayPal,Delivered
18,T019,2026-01-10,C1017,Phone Earbuds,NaN,1.0,69.99,69.99,Apple Pay,Processing
19,T020,2026-01-10,C1018,NaN,Office,1.0,49.99,49.99,Credit Card,Shipped

In [6]:
df.describe()

        quantity  unit_price  total_amount
count  17.000000   19.000000     18.000000
mean    1.764706   45.727895     57.485000
std     1.147247   57.297496     57.352928
min     1.000000    5.990000      9.990000
25%     1.000000   15.490000     24.992500
50%     1.000000   24.990000     39.970000
75%     2.000000   47.990000     65.235000
max     5.000000  249.990000    249.990000

In [7]:
df.dtypes

transaction_id     object
date               object
customer_id        object
product_name       object
category           object
quantity          float64
unit_price        float64
total_amount      float64
payment_method     object
order_status       object
dtype: object

In [8]:
# Handling Missing Values
df.isnull().any()

transaction_id    False
date               True
customer_id        True
product_name       True
category           True
quantity           True
unit_price         True
total_amount       True
payment_method     True
order_status       True
dtype: bool

In [9]:
df.isnull().sum()

transaction_id    0
date              1
customer_id       3
product_name      3
category          4
quantity          3
unit_price        1
total_amount      2
payment_method    2
order_status      1
dtype: int64

In [10]:
df_fillna = df.fillna(0)

In [11]:
## filling missin values with the mean of the coilumn
# df['Sales_fillNA']=df['category'].fillna(df['category'].mean())
# เติมด้วยค่าที่ฮิตที่สุดในหมวดหมู่
most_frequent = df['category'].mode()[0] 
df['category_filled'] = df['category'].fillna(most_frequent)
df

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status,category_filled
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered,Electronics
1,T002,2026-01-01,C1002,USB-C Cable,NaN,2.0,12.50,25.00,PayPal,Shipped,Electronics
2,T003,2026-01-02,C1003,Phone Case,Accessories,NaN,15.99,15.99,Debit Card,Processing,Accessories
3,T004,2026-01-02,NaN,Laptop Stand,Office,3.0,34.99,104.97,Credit Card,Delivered,Office
4,T005,2026-01-03,C1005,Keyboard Mechanical,Electronics,1.0,NaN,89.99,Apple Pay,Shipped,Electronics
5,T006,2026-01-03,C1006,NaN,Electronics,1.0,249.99,249.99,Credit Card,Processing,Electronics
6,T007,2026-01-04,C1001,Webcam HD,Electronics,1.0,79.99,NaN,PayPal,Delivered,Electronics
7,T008,2026-01-04,C1007,Desk Lamp LED,Office,2.0,22.50,45.00,NaN,Shipped,Office
8,T009,2026-01-05,C1008,Phone Screen Protector,Accessories,5.0,8.99,44.95,Debit Card,NaN,Accessories
9,T010,2026-01-05,C1009,External SSD 1TB,Electronics,NaN,119.99,119.99,Credit Card,Processing,Electronics
10,T011,2026-01-06,C1010,Mouse Pad,NaN,1.0,9.99,9.99,PayPal,Shipped,Electronics
11,T012,2026-01-06,NaN,HDMI Cable,Electronics,3.0,5.99,17.97,Credit Card,Delivered,Electronics
12,T013,2026-01-07,C1012,Notebook Set,NaN,2.0,14.99,29.98,Apple Pay,Processing,Electronics
13,T014,2026-01-07,C1013,NaN,Accessories,1.0,19.99,19.99,NaN,Shipped,Accessories
14,T015,2026-01-08,C1002,Portable Charger,Electronics,1.0,45.99,NaN,PayPal,Delivered,Electronics
15,T016,NaN,C1014,Desk Organizer,Office,1.0,24.99,24.99,Debit Card,Processing,Office
16,T017,2026-01-09,C1015,USB Hub 7 Port,Electronics,NaN,34.99,34.99,Credit Card,Shipped,Electronics
17,T018,2026-01-09,NaN,Pen Set Premium,Office,3.0,16.99,50.97,PayPal,Delivered,Office
18,T019,2026-01-10,C1017,Phone Earbuds,NaN,1.0,69.99,69.99,Apple Pay,Processing,Electronics
19,T020,2026-01-10,C1018,NaN,Office,1.0,49.99,49.99,Credit Card,Shipped,Office

In [12]:
df['unit_price_filled']=df['unit_price'].fillna(df['unit_price'].mean())

In [13]:
df.head(5)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status,category_filled,unit_price_filled
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered,Electronics,29.990000
1,T002,2026-01-01,C1002,USB-C Cable,NaN,2.0,12.50,25.00,PayPal,Shipped,Electronics,12.500000
2,T003,2026-01-02,C1003,Phone Case,Accessories,NaN,15.99,15.99,Debit Card,Processing,Accessories,15.990000
3,T004,2026-01-02,NaN,Laptop Stand,Office,3.0,34.99,104.97,Credit Card,Delivered,Office,34.990000
4,T005,2026-01-03,C1005,Keyboard Mechanical,Electronics,1.0,NaN,89.99,Apple Pay,Shipped,Electronics,45.727895

In [14]:
df.dtypes

transaction_id        object
date                  object
customer_id           object
product_name          object
category              object
quantity             float64
unit_price           float64
total_amount         float64
payment_method        object
order_status          object
category_filled       object
unit_price_filled    float64
dtype: object

In [15]:
## Reaming column
df.rename(columns={'date':'date_date'})
df.head(5)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status,category_filled,unit_price_filled
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered,Electronics,29.990000
1,T002,2026-01-01,C1002,USB-C Cable,NaN,2.0,12.50,25.00,PayPal,Shipped,Electronics,12.500000
2,T003,2026-01-02,C1003,Phone Case,Accessories,NaN,15.99,15.99,Debit Card,Processing,Accessories,15.990000
3,T004,2026-01-02,NaN,Laptop Stand,Office,3.0,34.99,104.97,Credit Card,Delivered,Office,34.990000
4,T005,2026-01-03,C1005,Keyboard Mechanical,Electronics,1.0,NaN,89.99,Apple Pay,Shipped,Electronics,45.727895

In [16]:
## change datatype
# df['Price']=df['unit_price'].astype(float)
df['Price']=df['unit_price'].fillna(df['unit_price'].mean()).astype(int)
df.head(1)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status,category_filled,unit_price_filled,Price
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered,Electronics,29.99,29

In [17]:
df['new_price']=df['unit_price'].apply(lambda x:x*2)
df.head(5)

,transaction_id,date,customer_id,product_name,category,quantity,unit_price,total_amount,payment_method,order_status,category_filled,unit_price_filled,Price,new_price
0,T001,2026-01-01,C1001,Wireless Mouse,Electronics,1.0,29.99,29.99,Credit Card,Delivered,Electronics,29.990000,29,59.98
1,T002,2026-01-01,C1002,USB-C Cable,NaN,2.0,12.50,25.00,PayPal,Shipped,Electronics,12.500000,12,25.00
2,T003,2026-01-02,C1003,Phone Case,Accessories,NaN,15.99,15.99,Debit Card,Processing,Accessories,15.990000,15,31.98
3,T004,2026-01-02,NaN,Laptop Stand,Office,3.0,34.99,104.97,Credit Card,Delivered,Office,34.990000,34,69.98
4,T005,2026-01-03,C1005,Keyboard Mechanical,Electronics,1.0,NaN,89.99,Apple Pay,Shipped,Electronics,45.727895,45,NaN

In [18]:
## Das Agregating and Grouping
group_mean = df.groupby('product_name')['Price'].mean()
group_mean

product_name
Desk Lamp LED              22.0
Desk Organizer             24.0
External SSD 1TB          119.0
HDMI Cable                  5.0
Keyboard Mechanical        45.0
Laptop Stand               34.0
Mouse Pad                   9.0
Notebook Set               14.0
Pen Set Premium            16.0
Phone Case                 15.0
Phone Earbuds              69.0
Phone Screen Protector      8.0
Portable Charger           45.0
USB Hub 7 Port             34.0
USB-C Cable                12.0
Webcam HD                  79.0
Wireless Mouse             29.0
Name: Price, dtype: float64

In [19]:
df.groupby(['product_name','category'])['quantity'].sum()

product_name            category
Desk Lamp LED           Office         2.0
Desk Organizer          Office         1.0
External SSD 1TB        Electronics    0.0
HDMI Cable              Electronics    3.0
Keyboard Mechanical     Electronics    1.0
Laptop Stand            Office         3.0
Pen Set Premium         Office         3.0
Phone Case              Accessories    0.0
Phone Screen Protector  Accessories    5.0
Portable Charger        Electronics    1.0
USB Hub 7 Port          Electronics    0.0
Webcam HD               Electronics    1.0
Wireless Mouse          Electronics    1.0
Name: quantity, dtype: float64

In [20]:
# arggregate multi function 
# สรุปข้อมูลคอลัมน์ total_amount โดยหาทั้ง ผลรวม, ค่าเฉลี่ย, และค่ามากสุด
df.groupby('category')['total_amount'].agg(['sum', 'mean', 'max'])

                sum       mean     max
category
Accessories   80.93  26.976667   44.95
Electronics  542.92  90.486667  249.99
Office       275.92  55.184000  104.97

In [21]:
## Merging and join dataframe


df1= pd.DataFrame({'key':['A','B','c'], 'Value1': [1,2,3]})
df2= pd.DataFrame({'key':['A','B','d'], 'Value1': [4,5,6]})

In [22]:
df1

  key  Value1
0   A       1
1   B       2
2   c       3

In [23]:
df2

  key  Value1
0   A       4
1   B       5
2   d       6

In [24]:
## Merge Dataframe on the  ' key columns  '


pd.merge(df1,df2,on="key",how="inner")

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [25]:
pd.merge(df1,df2,on="key",how="outer")

  key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   c       3.0       NaN
3   d       NaN       6.0

In [26]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   c         3       NaN

In [27]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   d       NaN         6