In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (2.1.3)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asman_s\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [4]:
#series คือโครงสร้างข้อมูลแบบหนึ่งใน Pandas ที่ใช้เก็บข้อมูลในรูปแบบของลำดับ (1D) โดยมีการจัดเรียงข้อมูลเป็นลำดับและมีป้ายกำกับ (index) ที่สามารถใช้ในการเข้าถึงข้อมูลได้อย่างง่ายดาย


import pandas as pd 
data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
# create a series from a dictionary

data_dict = {'a': 1, 'b': 2, 'c': 3}
series_from_dict = pd.Series(data_dict)
print( series_from_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
pd.Series(data, index=index)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [10]:
# dataframe
#create dataframe from  dictionary

data = {
    'Name':['asman','john','jack'],
    'Age':[25,30,45],
    'City':['Bankok','New York' , 'Florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  asman   25    Bankok
1   john   30  New York
2   jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [32]:
## Create a data frame from a list of dictionary
data = [
    {'Name':'Asman',
     'Age':23 ,
     'City':'Bankok'},
     
    {'Name':'BB',
     'Age':41 ,
     'City':'Chicago'},

    {'Name':'ww',
     'Age':31 ,
     'City':'Bankok'},

    {'Name':'qq',
     'Age':75 ,
     'City':'Bankok'},
     

]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age     City
0  Asman   23   Bankok
1     BB   41  Chicago
2     ww   31   Bankok
3     qq   75   Bankok
<class 'pandas.core.frame.DataFrame'>

In [14]:
df = pd.read_csv('sales_data.csv')

In [16]:
df.head(5)

,transaction_id,date,time,customer_id,product_id,product_name,category,quantity,unit_price,total_amount,payment_method,shipping_address,order_status,customer_country
0,T001,2026-01-01,08:15:00,C1001,P501,Wireless Mouse,Electronics,1,29.99,29.99,Credit Card,New York USA,Delivered,USA
1,T002,2026-01-01,09:32:15,C1002,P502,USB-C Cable,Electronics,2,12.50,25.00,PayPal,London UK,Shipped,UK
2,T003,2026-01-01,10:45:30,C1003,P503,Phone Case,Accessories,1,15.99,15.99,Debit Card,Toronto Canada,Processing,Canada
3,T004,2026-01-01,11:20:45,C1004,P504,Laptop Stand,Office,3,34.99,104.97,Credit Card,Sydney Australia,Delivered,Australia
4,T005,2026-01-01,12:10:00,C1005,P505,Keyboard Mechanical,Electronics,1,89.99,89.99,Apple Pay,Berlin Germany,Shipped,Germany

In [17]:
df.tail(5)

,transaction_id,date,time,customer_id,product_id,product_name,category,quantity,unit_price,total_amount,payment_method,shipping_address,order_status,customer_country
15,T016,2026-01-02,13:20:30,C1014,P516,Desk Organizer,Office,1,24.99,24.99,Debit Card,Seoul South Korea,Processing,South Korea
16,T017,2026-01-02,14:50:45,C1015,P517,USB Hub 7 Port,Electronics,1,34.99,34.99,Credit Card,Singapore,Shipped,Singapore
17,T018,2026-01-02,15:35:20,C1016,P518,Pen Set Premium,Office,3,16.99,50.97,PayPal,Bangkok Thailand,Delivered,Thailand
18,T019,2026-01-02,16:45:00,C1017,P519,Phone Earbuds,Electronics,1,69.99,69.99,Apple Pay,Buenos Aires Argentina,Processing,Argentina
19,T020,2026-01-02,17:20:15,C1018,P520,Monitor Stand Adjustable,Office,1,49.99,49.99,Credit Card,São Paulo Brazil,Shipped,Brazil

In [21]:
## Accessin Data from Dataframe

df

    Name  Age     City
0  Asman   23   Bankok
1     BB   23  Chicago
2     ww   23   Bankok
3     qq   23   Bankok

In [22]:
df['Name']

0    Asman
1       BB
2       ww
3       qq
Name: Name, dtype: object

In [24]:
df.iloc[0]

Name     Asman
Age         23
City    Bankok
Name: 0, dtype: object

In [25]:
df.loc[0]

Name     Asman
Age         23
City    Bankok
Name: 0, dtype: object

In [27]:
df.loc[0][0]

C:\Users\asman_s\AppData\Local\Temp\ipykernel_948\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Asman'

In [33]:
df

    Name  Age     City
0  Asman   23   Bankok
1     BB   41  Chicago
2     ww   31   Bankok
3     qq   75   Bankok

In [34]:
# Accescing  a specifiles alement 
df['Name']

0    Asman
1       BB
2       ww
3       qq
Name: Name, dtype: object

In [35]:
df.at[1,'Age']

41

In [36]:
df.at[2,'Name']

'ww'

In [39]:
# Accescing  a specifiles alement  using iat
df.iat[2,2]

'Bankok'

In [40]:
## DATA Manipulation with  Dataframe
df

    Name  Age     City
0  Asman   23   Bankok
1     BB   41  Chicago
2     ww   31   Bankok
3     qq   75   Bankok

In [ ]:
#adding a column Salary 
df['Salary']=[50000,3000,6000,10000]

In [43]:
df

    Name  Age     City  Salary
0  Asman   23   Bankok   50000
1     BB   41  Chicago    3000
2     ww   31   Bankok    6000
3     qq   75   Bankok   10000

In [ ]:
## remove a column
df.drop('Salary',axis=1) # 0 คือ บนลงล่าง" (วิ่งผ่านแต่ละแถว)  1 คือ  ซ้ายไปขวา" (วิ่งข้ามคอลัมน์)

    Name  Age     City
0  Asman   23   Bankok
1     BB   41  Chicago
2     ww   31   Bankok
3     qq   75   Bankok

In [45]:
df

    Name  Age     City  Salary
0  Asman   23   Bankok   50000
1     BB   41  Chicago    3000
2     ww   31   Bankok    6000
3     qq   75   Bankok   10000

In [46]:
df.drop('Salary',axis=1,inplace=True) # inplace= true  คือลบจริงจากข้อมูล ถ้าไม่ใส่มันคือการลบชั่วคราว

In [48]:
df

    Name  Age     City
0  Asman   23   Bankok
1     BB   41  Chicago
2     ww   31   Bankok
3     qq   75   Bankok

In [50]:
# add age to the column
df['Age']=df['Age']+1

In [51]:
df

    Name  Age     City
0  Asman   24   Bankok
1     BB   42  Chicago
2     ww   32   Bankok
3     qq   76   Bankok

In [55]:
df.drop(0,inplace=True)

In [56]:
df

  Name  Age     City
1   BB   42  Chicago
2   ww   32   Bankok
3   qq   76   Bankok

In [57]:
data

[{'Name': 'Asman', 'Age': 23, 'City': 'Bankok'},
 {'Name': 'BB', 'Age': 41, 'City': 'Chicago'},
 {'Name': 'ww', 'Age': 31, 'City': 'Bankok'},
 {'Name': 'qq', 'Age': 75, 'City': 'Bankok'}]

In [60]:
sale_data = pd.read_csv('sales_data.csv')
sale_data.head(5)

,transaction_id,date,time,customer_id,product_id,product_name,category,quantity,unit_price,total_amount,payment_method,shipping_address,order_status,customer_country
0,T001,2026-01-01,08:15:00,C1001,P501,Wireless Mouse,Electronics,1,29.99,29.99,Credit Card,New York USA,Delivered,USA
1,T002,2026-01-01,09:32:15,C1002,P502,USB-C Cable,Electronics,2,12.50,25.00,PayPal,London UK,Shipped,UK
2,T003,2026-01-01,10:45:30,C1003,P503,Phone Case,Accessories,1,15.99,15.99,Debit Card,Toronto Canada,Processing,Canada
3,T004,2026-01-01,11:20:45,C1004,P504,Laptop Stand,Office,3,34.99,104.97,Credit Card,Sydney Australia,Delivered,Australia
4,T005,2026-01-01,12:10:00,C1005,P505,Keyboard Mechanical,Electronics,1,89.99,89.99,Apple Pay,Berlin Germany,Shipped,Germany

In [62]:
print("statitical summary:\n", sale_data.describe)

statitical summary:
 <bound method NDFrame.describe of    transaction_id        date      time customer_id product_id  \
0            T001  2026-01-01  08:15:00       C1001       P501
1            T002  2026-01-01  09:32:15       C1002       P502
2            T003  2026-01-01  10:45:30       C1003       P503
3            T004  2026-01-01  11:20:45       C1004       P504
4            T005  2026-01-01  12:10:00       C1005       P505
5            T006  2026-01-01  13:55:20       C1006       P506
6            T007  2026-01-01  14:30:15       C1001       P507
7            T008  2026-01-01  15:45:50       C1007       P508
8            T009  2026-01-01  16:20:30       C1008       P509
9            T010  2026-01-01  17:15:00       C1009       P510
10           T011  2026-01-02  08:00:00       C1010       P511
11           T012  2026-01-02  09:30:45       C1011       P512
12           T013  2026-01-02  10:15:20       C1012       P513
13           T014  2026-01-02  11:45:00       C1013       P514
14           T015  2026-01-02  12:30:15       C1002       P515
15           T016  2026-01-02  13:20:30       C1014       P516
16           T017  2026-01-02  14:50:45       C1015       P517
17           T018  2026-01-02  15:35:20       C1016       P518
18           T019  2026-01-02  16:45:00       C1017       P519
19           T020  2026-01-02  17:20:15       C1018       P520

                product_name     category  quantity  unit_price  total_amount  \
0             Wireless Mouse  Electronics         1       29.99         29.99
1                USB-C Cable  Electronics         2       12.50         25.00
2                 Phone Case  Accessories         1       15.99         15.99
3               Laptop Stand       Office         3       34.99        104.97
4        Keyboard Mechanical  Electronics         1       89.99         89.99
5            Monitor 27 inch  Electronics         1      249.99        249.99
6                  Webcam HD  Electronics         1       79.99         79.99
7              Desk Lamp LED       Office         2       22.50         45.00
8     Phone Screen Protector  Accessories         5        8.99         44.95
9           External SSD 1TB  Electronics         1      119.99        119.99
10                 Mouse Pad  Accessories         1        9.99          9.99
11                HDMI Cable  Electronics         3        5.99         17.97
12              Notebook Set       Office         2       14.99         29.98
13           Phone Mount Car  Accessories         1       19.99         19.99
14          Portable Charger  Electronics         1       45.99         45.99
15            Desk Organizer       Office         1       24.99         24.99
16            USB Hub 7 Port  Electronics         1       34.99         34.99
17           Pen Set Premium       Office         3       16.99         50.97
18             Phone Earbuds  Electronics         1       69.99         69.99
19  Monitor Stand Adjustable       Office         1       49.99         49.99

   payment_method        shipping_address order_status customer_country
0     Credit Card            New York USA    Delivered              USA
1          PayPal               London UK      Shipped               UK
2      Debit Card          Toronto Canada   Processing           Canada
3     Credit Card        Sydney Australia    Delivered        Australia
4       Apple Pay          Berlin Germany      Shipped          Germany
5     Credit Card            Paris France   Processing           France
6          PayPal            New York USA    Delivered              USA
7     Credit Card             Tokyo Japan      Shipped            Japan
8      Debit Card          Toronto Canada    Delivered           Canada
9     Credit Card            Mumbai India   Processing            India
10         PayPal      Mexico City Mexico      Shipped           Mexico
11    Credit Card            Madrid Spain    Delivered            Spain
12      Apple Pay   Amsterdam Netherlands   Processing      Netherlands
13    Credit Card               Dubai UAE      Shipped              UAE
14         PayPal               London UK    Delivered               UK
15     Debit Card       Seoul South Korea   Processing      South Korea
16    Credit Card               Singapore      Shipped        Singapore
17         PayPal        Bangkok Thailand    Delivered         Thailand
18      Apple Pay  Buenos Aires Argentina   Processing        Argentina
19    Credit Card        São Paulo Brazil      Shipped           Brazil  >